CREATE DATABASE ESTACIONAMENTO_ANDRE_ED;

GO

USE ESTACIONAMENTO_ANDRE_ED

GO

CREATE TABLE EST_ESTACIONAMENTO(
EST_IN_ID INT NOT NULL IDENTITY CONSTRAINT EST_PK_ID PRIMARY KEY,
EST_CH_PLACA CHAR(7) NOT NULL CONSTRAINT EST_UK_PLACA UNIQUE CONSTRAINT EST_CK_PLACA
CHECK(EST_CH_PLACA LIKE '[A-Z][A-Z][A-Z][0-9][A-Z0-9][0-9][0-9]') CONSTRAINT EST_FK_PLACA FOREIGN KEY REFERENCES EST_CARRO(CAR_CH_PLACA),
EST_ST_NOME VARCHAR(100) NOT NULL,
EST_ST_TELEFONE VARCHAR(12) NOT NULL,
EST_DT_ENTRADA DATE NULL);

CREATE TABLE EST_CARRO(
CAR_IN_ID INT NOT NULL IDENTITY,
CAR_CH_PLACA CHAR(7) NOT NULL CONSTRAINT CAR_PK_PLACA PRIMARY KEY 
CONSTRAINT CAR_CK_PLACA CHECK(CAR_CH_PLACA LIKE '[A-Z][A-Z][A-Z][0-9][A-Z0-9][0-9][0-9]'),
CAR_ST_NOME VARCHAR(20) NOT NULL,
CAR_ST_COR VARCHAR(10) NOT NULL,
CAR_RE_VALOR NUMERIC(10,2) NOT NULL CONSTRAINT CAR_DF_VALOR DEFAULT 0,
CAR_DT_FABRICACAO DATE NOT NULL,
CAR_ST_CHASSI VARCHAR(16) NOT NULL CONSTRAINT CAR_UK_CHASSI UNIQUE)




